### PR TITLE
Added searchbar and made to-dos searchable

### PR DESCRIPTION
**Pull request by te-sa**
I added a search bar to the main screen and modified the RecyclerAdapter to display the search results.

### CODE REVIEW

**Review by justino599 — CHANGES_REQUESTED** [review]
When filters are applied, the search shows items that do not match the filter

**Comment by justino599** [comment]
Also, deleting a task while in search doesn't delete the right task. Probably an index issue

**Comment by te-sa** [comment]
made the requested changes, please test again

**Review by justino599 — APPROVED** [review]

**Comment by justino599** [comment]
Sorry for the delayed review, must've missed the email requesting the review

**Pull request merged**
